drop table if exists employee;
create table employee(
id int primary key GENERATED BY DEFAULT AS IDENTITY,
name varchar(45) default null,
email varchar(70) default null,
phone varchar(45) default null,
address varchar(250) default null
);
